import {
  BotIcon,
  CalendarClockIcon,
  CommandIcon,
  DatabaseIcon,
  FolderOpenIcon,
  GlobeIcon,
  HardDriveIcon,
  LaptopIcon,
  LayoutGridIcon,
  LibraryIcon,
  PlusIcon,
  SearchIcon,
  SparklesIcon,
  WrenchIcon,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";

export type WorkspaceToolSectionId = "pinned" | "available";
export type SidebarSectionId = "quick" | "workspace" | "tools";
export type WorkspaceToolAction = "route" | "search" | "toolbox";

export type WorkspaceToolItem = {
  id: string;
  title: string;
  description: string;
  href: string;
  icon: LucideIcon;
  /** Default section from registry; runtime section is derived from pinnedIds. */
  section: WorkspaceToolSectionId;
  action?: WorkspaceToolAction;
  badge?: string;
  shortcut?: string;
};

export type WorkspaceToolSection = {
  id: WorkspaceToolSectionId;
  title: string;
  items: WorkspaceToolItem[];
};

export type SidebarNavigationSection = {
  id: SidebarSectionId;
  title?: string;
  items: WorkspaceToolItem[];
};

// ---------------------------------------------------------------------------
// Tool registry
// ---------------------------------------------------------------------------

export const TOOL_REGISTRY: WorkspaceToolItem[] = [
  {
    id: "new-task",
    title: "New Task",
    description: "Start a fresh workspace task.",
    href: "/workspace/chats/new",
    icon: PlusIcon,
    section: "pinned",
    shortcut: "⌘K",
  },
  {
    id: "search",
    title: "Search",
    description: "Find tasks and workspace history.",
    href: "#search",
    icon: SearchIcon,
    section: "pinned",
    action: "search",
  },
  {
    id: "studio",
    title: "Studio",
    description: "Multimodal generation for images, video, and artifacts.",
    href: "#studio",
    icon: SparklesIcon,
    section: "pinned",
    badge: "Beta",
  },
  {
    id: "cli",
    title: "CLI",
    description: "Run the workspace directly from your terminal.",
    href: "#cli",
    icon: CommandIcon,
    section: "pinned",
    badge: "Beta",
  },
  {
    id: "knowledge",
    title: "Knowledge",
    description: "Manage the knowledge base your agents can use.",
    href: "#knowledge",
    icon: LibraryIcon,
    section: "pinned",
  },
  {
    id: "scheduled-tasks",
    title: "Scheduled Tasks",
    description: "Set recurring or one-time automated tasks.",
    href: "#scheduled-tasks",
    icon: CalendarClockIcon,
    section: "pinned",
  },
  {
    id: "datasources",
    title: "Datasources",
    description: "Connect professional data sources for richer work.",
    href: "#datasources",
    icon: DatabaseIcon,
    section: "pinned",
  },
  {
    id: "toolbox",
    title: "Toolbox",
    description: "Browse, pin, and launch workspace tools.",
    href: "#toolbox",
    icon: WrenchIcon,
    section: "pinned",
    action: "toolbox",
  },
  {
    id: "new-agent",
    title: "New Agent",
    description: "Create a custom agent with a dedicated prompt and tools.",
    href: "/workspace/agents/new",
    icon: BotIcon,
    section: "available",
  },
  {
    id: "agents",
    title: "Agents",
    description: "View and manage your custom agents.",
    href: "/workspace/agents",
    icon: BotIcon,
    section: "available",
  },
  {
    id: "drive",
    title: "Drive",
    description: "Manage files generated by your tasks.",
    href: "#drive",
    icon: HardDriveIcon,
    section: "available",
  },
  {
    id: "computer",
    title: "Computer",
    description: "Control a cloud computer with AI assistance.",
    href: "#computer",
    icon: LaptopIcon,
    section: "available",
  },
  {
    id: "pages",
    title: "Pages",
    description: "Manage web pages generated from your work.",
    href: "#pages",
    icon: GlobeIcon,
    section: "available",
  },
  {
    id: "use-cases",
    title: "Use Cases",
    description: "Explore curated workflow templates.",
    href: "#use-cases",
    icon: LayoutGridIcon,
    section: "available",
  },
  {
    id: "files",
    title: "Files",
    description: "Browse local workspace files.",
    href: "#files",
    icon: FolderOpenIcon,
    section: "available",
  },
];

// ---------------------------------------------------------------------------
// IDs that are always present in sidebar regardless of pin state
// ---------------------------------------------------------------------------

const ALWAYS_SIDEBAR_IDS = new Set(["new-task", "search"]);
/** IDs excluded from the toolbox dialog entirely */
const TOOLBOX_EXCLUDED_IDS = new Set([
  "new-task",
  "search",
  "toolbox",
  "new-agent",
]);
/** IDs excluded from the sidebar regardless of pin state */
const SIDEBAR_EXCLUDED_IDS = new Set(["new-agent"]);

// ---------------------------------------------------------------------------
// Default pinned IDs (from the registry's `section: "pinned"`)
// ---------------------------------------------------------------------------

const DEFAULT_PINNED_IDS: string[] = TOOL_REGISTRY.filter(
  (t) => t.section === "pinned",
).map((t) => t.id);

const STORAGE_KEY = "prism:pinned-tool-ids";

function loadPinnedIds(): Set<string> {
  if (typeof window === "undefined") return new Set(DEFAULT_PINNED_IDS);
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return new Set(DEFAULT_PINNED_IDS);
    const parsed: string[] = JSON.parse(raw);
    // Validate that stored IDs still exist in the registry
    const validIds = new Set(TOOL_REGISTRY.map((t) => t.id));
    const filtered = parsed.filter((id) => validIds.has(id));
    return new Set(filtered.length ? filtered : DEFAULT_PINNED_IDS);
  } catch {
    return new Set(DEFAULT_PINNED_IDS);
  }
}

function savePinnedIds(ids: Set<string>) {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify([...ids]));
  } catch {
    // Ignore storage errors
  }
}

function getToolById(id: string): WorkspaceToolItem {
  const tool = TOOL_REGISTRY.find((item) => item.id === id);
  if (!tool) {
    throw new Error(`Unknown workspace tool: ${id}`);
  }
  return tool;
}

// ---------------------------------------------------------------------------
// Hook: usePinnedTools
// ---------------------------------------------------------------------------

export function usePinnedTools() {
  const [pinnedIds, setPinnedIds] = useState<Set<string>>(loadPinnedIds);

  // Sync to localStorage whenever pinnedIds changes
  useEffect(() => {
    savePinnedIds(pinnedIds);
  }, [pinnedIds]);

  const isPinned = useCallback((id: string) => pinnedIds.has(id), [pinnedIds]);

  const togglePin = useCallback((id: string) => {
    setPinnedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        // Don't unpin always-pinned items (new-task, search, toolbox)
        if (ALWAYS_SIDEBAR_IDS.has(id) || id === "toolbox") return prev;
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  }, []);

  const toolboxSections = useMemo<WorkspaceToolSection[]>(() => {
    const pinned = TOOL_REGISTRY.filter(
      (t) => pinnedIds.has(t.id) && !TOOLBOX_EXCLUDED_IDS.has(t.id),
    );
    const available = TOOL_REGISTRY.filter(
      (t) => !pinnedIds.has(t.id) && !TOOLBOX_EXCLUDED_IDS.has(t.id),
    );
    return [
      { id: "pinned", title: "Pinned", items: pinned },
      { id: "available", title: "Available Tools", items: available },
    ];
  }, [pinnedIds]);

  const sidebarSections = useMemo<SidebarNavigationSection[]>(() => {
    // Quick section: always-present items
    const quickItems = ALWAYS_SIDEBAR_IDS
      ? [...ALWAYS_SIDEBAR_IDS].map(getToolById)
      : [];
    // Workspace section: pinned items not in quick or tools
    const workspaceIds = TOOL_REGISTRY.filter(
      (t) =>
        pinnedIds.has(t.id) &&
        !ALWAYS_SIDEBAR_IDS.has(t.id) &&
        t.id !== "toolbox" &&
        !SIDEBAR_EXCLUDED_IDS.has(t.id),
    ).map((t) => t.id);
    // Tools section: always show toolbox
    return [
      { id: "quick", items: quickItems },
      { id: "workspace", items: workspaceIds.map(getToolById) },
      { id: "tools", items: [getToolById("toolbox")] },
    ];
  }, [pinnedIds]);

  return { pinnedIds, isPinned, togglePin, toolboxSections, sidebarSections };
}

// ---------------------------------------------------------------------------
// Pure helpers (exported for testing)
// ---------------------------------------------------------------------------

export function buildToolboxSections(
  pinnedIds: Set<string>,
): WorkspaceToolSection[] {
  const pinned = TOOL_REGISTRY.filter(
    (t) => pinnedIds.has(t.id) && !TOOLBOX_EXCLUDED_IDS.has(t.id),
  );
  const available = TOOL_REGISTRY.filter(
    (t) => !pinnedIds.has(t.id) && !TOOLBOX_EXCLUDED_IDS.has(t.id),
  );
  return [
    { id: "pinned", title: "Pinned", items: pinned },
    { id: "available", title: "Available Tools", items: available },
  ];
}

export function buildSidebarSections(
  pinnedIds: Set<string>,
): SidebarNavigationSection[] {
  const quickItems = [...ALWAYS_SIDEBAR_IDS].map(getToolById);
  const workspaceIds = TOOL_REGISTRY.filter(
    (t) =>
      pinnedIds.has(t.id) &&
      !ALWAYS_SIDEBAR_IDS.has(t.id) &&
      t.id !== "toolbox" &&
      !SIDEBAR_EXCLUDED_IDS.has(t.id),
  ).map((t) => t.id);
  return [
    { id: "quick", items: quickItems },
    { id: "workspace", items: workspaceIds.map(getToolById) },
    { id: "tools", items: [getToolById("toolbox")] },
  ];
}
